from setuptools import setup, find_packages

setup(
    name='pypdf',  # This should match the name you want for your package
    version='0.1',  # Update the version number as appropriate
    packages=find_packages(),
    # Include additional fields as necessary:
    description='A pure-python PDF library capable of splitting, merging, cropping, and transforming the pages of PDF files',  # Optional
    author='Phan Thanh Duy',  # Optional
    author_email='community',  # Optional
    url='https://github.com/py-pdf/pypdf',  # Optional
    license='MIT',  # Optional, specify the license as appropriate
    install_requires=[
        # List any dependencies that pypdf needs, for example:
        # see here: https://github.com/py-pdf/pypdf/blob/main/requirements/dev.txt
        # This file is autogenerated by pip-compile with python 3.7
        # To update, run:
        #
        #    pip-compile requirements/dev.in
        #
        'black == 23.3.0'
        # via -r requirements/dev.in
        'build == 1.0.3'
        # via pip-tools
        'certifi == 2023.7.22'
        # via requests
        'cfgv == 3.3.1'
        # via pre-commit
        'charset - normalizer == 3.3.1'
        # via requests
        'click == 8.1.7'
        # via
        #   black
        #   pip-tools
        'coverage[toml] == 7.2.7'
        # via pytest-cov
        'distlib == 0.3.7'
        # via virtualenv
        'docutils == 0.20.1'
        # via flit
        'exceptiongroup == 1.1.3'
        # via pytest
        'filelock == 3.12.2'
        # via virtualenv
        'flit == 3.9.0'
        # via -r requirements/dev.in
        'flit - core == 3.9.0'
        # via flit
        'identify == 2.5.24'
        # via pre-commit
        'idna == 3.4'
        # via requests
        'importlib - metadata == 6.7.0'
        # via
        #   build
        #   click
        #   pre-commit
        #   pytest
        #   virtualenv
        'iniconfig == 2.0.0'
        # via pytest
        'mypy - extensions == 1.0.0'
        # via black
        'nodeenv == 1.8.0'
        # via pre-commit
        'packaging == 23.2'
        # via
        #   black
        #   build
        #   pytest
        'pathspec == 0.11.2'
        # via black
        'pillow == 9.5.0'
        # via -r requirements/dev.in
        'pip - tools == 6.14.0'
        # via -r requirements/dev.in
        'platformdirs == 3.11.0'
        # via
        #   black
        #   virtualenv
        'pluggy == 1.2.0'
        # via pytest
        'pre - commit == 2.17.0'
        # via -r requirements/dev.in
        'pyproject - hooks == 1.0.0'
        # via build
        'pytest == 7.4.3'
        # via pytest-cov
        'pytest - cov == 4.1.0'
        # via -r requirements/dev.in
        'pyyaml == 6.0.1'
        # via pre-commit
        'requests == 2.31.0'
        # via flit
        'toml == 0.10.2'
        # via pre-commit
        'tomli == 2.0.1'
        # via
        #   black
        #   build
        #   coverage
        #   pip-tools
        #   pytest
        'tomli - w == 1.0.0'
        # via flit
        'typed - ast == 1.5.5'
        # via black
        'typing - extensions == 4.7.1'
        # via
        #   black
        #   importlib-metadata
        #   platformdirs
        'urllib3 == 2.0.7'
        # via requests
        'virtualenv == 20.24.6'
        # via pre-commit
        'wheel == 0.41.2'
        # via
        #   -r requirements/dev.in
        #   pip-tools
        'zipp == 3.15.0'
        # via importlib-metadata

        # The following packages are considered to be unsafe in a requirements file:
        # pip
        # setuptools
    ],
    classifiers=[
        'Development Status :: 3 - Alpha',  # Update as appropriate
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
    ],
    python_requires='>=3.7',  # Specify which Python versions you support
)
